In [1]:
import numpy as np
from numpy import genfromtxt

In [4]:
# genfromtxt just makes an array from a txt file
data  = genfromtxt("C:/OpenCV/DATA/bank_note_data.txt", delimiter = ",")
data
# 0 is forgery, 1 means its authentic (look in last column)

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X = features
y = labels

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# this essentially splits our test cases into two parts. Test or Train group. 
# test_size = percent of cases which is used to test. That means 66% went to train group.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
len(X_train)

919

In [17]:
len(X)

1372

In [18]:
len(X_test)

453

In [19]:
from sklearn.preprocessing import MinMaxScaler

scaler_object = MinMaxScaler()

In [20]:
# fit() just finds the max and min
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaledXTrain = scaler_object.transform(X_train)
# we only fit to the training data, otherwise we assume knowledge of the test data. idky tbh
scaledXTest = scaler_object.transform(X_test)

In [22]:
scaledXTrain.max()

1.0000000000000002

In [23]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [24]:
scaledXTrain

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
# layers of a nerual network
model = Sequential()
# input layer
model.add(Dense(4, input_dim = 4, activation = "relu"))
# hidden layer
model.add(Dense(8, activation = "relu"))
# output layer
model.add(Dense(1, activation = "sigmoid"))

In [27]:
# compiles the network
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [42]:
# Now train the model; 1 epoch means you went through all the training data 1 time
model.fit(scaledXTrain, y_train, epochs = 50, verbose = 2)

Epoch 1/50
 - 0s - loss: 0.0246 - acc: 0.9902
Epoch 2/50
 - 0s - loss: 0.0227 - acc: 0.9902


Epoch 3/50
 - 0s - loss: 0.0229 - acc: 0.9924
Epoch 4/50
 - 0s - loss: 0.0227 - acc: 0.9869
Epoch 5/50
 - 0s - loss: 0.0229 - acc: 0.9913
Epoch 6/50
 - 0s - loss: 0.0224 - acc: 0.9902
Epoch 7/50
 - 0s - loss: 0.0230 - acc: 0.9924
Epoch 8/50
 - 0s - loss: 0.0227 - acc: 0.9891
Epoch 9/50
 - 0s - loss: 0.0246 - acc: 0.9869
Epoch 10/50
 - 0s - loss: 0.0231 - acc: 0.9891
Epoch 11/50
 - 0s - loss: 0.0228 - acc: 0.9859
Epoch 12/50
 - 0s - loss: 0.0228 - acc: 0.9935
Epoch 13/50
 - 0s - loss: 0.0236 - acc: 0.9848
Epoch 14/50
 - 0s - loss: 0.0224 - acc: 0.9913
Epoch 15/50
 - 0s - loss: 0.0224 - acc: 0.9891
Epoch 16/50
 - 0s - loss: 0.0220 - acc: 0.9913
Epoch 17/50
 - 0s - loss: 0.0220 - acc: 0.9924
Epoch 18/50
 - 0s - loss: 0.0219 - acc: 0.9902
Epoch 19/50
 - 0s - loss: 0.0222 - acc: 0.9935
Epoch 20/50
 - 0s - loss: 0.0221 - acc: 0.9891
Epoch 21/50
 - 0s - loss: 0.0218 - acc: 0.9913
Epoch 22/50
 - 0s - loss: 0.0222 - acc: 0.9924
Epoch 23/50
 - 0s - loss: 0.0215 - acc: 0.9891
Epoch 24/50
 - 0s - 

In [31]:
model.metrics_names

['loss', 'acc']

In [32]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
# gives a list of the models predictions for the scaledXTest cases
predictions = model.predict_classes(scaledXTest)

# compares y_test(the right answers) with your own models "predictions." We see that we have 11 wrong (4 + 7).
confusion_matrix(y_test, predictions)

In [34]:
# this gives you how well you all the info
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.98      0.97      0.98       257
        1.0       0.96      0.98      0.97       196

avg / total       0.98      0.98      0.98       453



In [35]:
# this is how you save your model
model.save("mysupermodel.h5")

In [36]:
from keras.models import load_model


In [37]:
# this is how you load your saved model
newmodel = load_model("mysupermodel.h5")

In [38]:
# running our saved model again
newpredictions = newmodel.predict_classes(scaledXTest)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    